name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - uses: actions/checkout@v4

    # Build C# code
    - name: Build C# project
      run: dotnet build 
    
    # Run C# tests
    - name: Run C# tests
      run: dotnet test 

    # Build TypeScript code
    - name: Build TypeScript project
      run: npm run build
    
    # Run linter on TypeScript code
    - name: Run TypeScript linter
      run: npm run lint

    # Run TypeScript tests
    - name: Run TypeScript tests
      run: npm test
